export { default as Background } from './background/Background';
export { default as Icons } from './icons/Icons';
export { default as Education } from './slider/slides/education/Education';
export { default as Bio } from './slider/slides/bio/Bio';
export { default as Work } from './slider/slides/work/Work';
export { default as RecentWork } from './slider/slides/work/RecentWork';
export { default as Skills } from './slider/slides/skills/Skills';
export { default as Slider } from './slider/Slider';
export { default as Button } from './button/Button';
